version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      POSTGRES_CONN: "postgres://cnrprod1725773447-team-79619:cnrprod1725773447-team-79619@rc1b-5xmqy6bq501kls4m.mdb.yandexcloud.net:5432/cnrprod1725773447-team-79619"
      POSTGRES_JDBC_URL: "jdbc:postgresql://rc1b-5xmqy6bq501kls4m.mdb.yandexcloud.net:6432/cnrprod1725773447-team-79619"
      POSTGRES_USERNAME: "cnrprod1725773447-team-79619"
      POSTGRES_PASSWORD: "cnrprod1725773447-team-79619"
      POSTGRES_HOST: "rc1b-5xmqy6bq501kls4m.mdb.yandexcloud.net"
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: "cnrprod1725773447-team-79619"
    container_name: "avito-tech"