name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Set image tag
      id: vars
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ env.TAG }}

    - name: Run the Docker container
      run: docker run -d -p 8080:8080 my-image-name:${{ env.TAG }}

    - name: Test the application
      run: curl http://localhost:8080/health || echo "App failed to start"
